### ISSUE TITLE
Typo in SPEC.md -- "upstream" should be replaced with "downstream"

### ISSUE THREAD

**Issue by sanjay-saxena** [k3po/specification.wse#6]
In the Client Handshake Requirements in the Opening Handshake section, we currently have these two lines:

```
The first line is an http or https URL for upstream data transfer of the emulated WebSocket connection.

The second line is an http or https URL for upstream data transfer of the emulated WebSocket connection.
```

In the second line, "upstream" should be replaced with "downstream".

**Comment by jfallows** [comment]
Feel free to submit a pull request for this in future. :smiley:
